kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: onyxdb-agent-robot
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: onyxdb-agent-robot
automountServiceAccountToken: true
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: onyxdb-agent-robot
subjects:
  - kind: ServiceAccount
    name: onyxdb-agent-robot
roleRef:
  kind: Role
  name: onyxdb-agent-robot
  apiGroup: rbac.authorization.k8s.io
