apiVersion: v1
kind: Secret
metadata:
  name: onyxdb
  labels:
    app.kubernetes.io/name: onyxdb
    app.kubernetes.io/instance: onyxdb
stringData:
  ONYXDB_SELF_URL: "http://onyxdb.onyxdb.svc.cluster.local:9001"
  ONYXDB_SELF_NAMESPACE: "onyxdb"
  ONYXDB_NAMESPACES: "onyxdb"
  ONYXDB_STORAGE_CLASSES: "yc-network-hdd"
  ONYXDB_POSTGRES_URL: "jdbc:postgresql://postgres-onyxdb.onyxdb.svc.cluster.local:5432/onyxdb"
  ONYXDB_POSTGRES_USER: "onyxdb"
  ONYXDB_POSTGRES_PASSWORD: "qwerty"
  ONYXDB_REDIS_HOST: "redis-onyxdb.onyxdb.svc.cluster.local"
  ONYXDB_REDIS_PORT: "6379"
  ONYXDB_REDIS_USER: "onyxdb"
  ONYXDB_REDIS_PASSWORD: "qwerty"
  ONYXDB_CLICKHOUSE_URL: "jdbc:clickhouse://clickhouse-onyxdb.onyxdb.svc.cluster.local:8123/onyxdb"
  ONYXDB_CLICKHOUSE_USER: "onyxdb"
  ONYXDB_CLICKHOUSE_PASSWORD: "qwerty"
  ONYXDB_MINIO_URL: "http://minio.onyxdb.svc.cluster.local:9000"
  ONYXDB_MINIO_SECRET: "minio-onyxdb"
  ONYXDB_MINIO_BUCKET: "onyxdb"
  ONYXDB_VLOGS_URL: "http://vls-onyxdb.onyxdb.svc.cluster.local:9428"
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: onyxdb-robot
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/exec
      - services
      - persistentvolumeclaims
      - secrets
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
      - deletecollection
  - apiGroups:
      - apps
    resources:
      - deployments
      - replicasets
      - statefulsets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - batch
    resources:
      - cronjobs
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - psmdb.percona.com
    resources:
      - perconaservermongodbs
      - perconaservermongodbs/status
      - perconaservermongodbs/finalizers
      - perconaservermongodbbackups
      - perconaservermongodbbackups/status
      - perconaservermongodbbackups/finalizers
      - perconaservermongodbrestores
      - perconaservermongodbrestores/status
      - perconaservermongodbrestores/finalizers
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - operator.victoriametrics.com
    resources:
      - vmservicescrapes
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: onyxdb-robot
automountServiceAccountToken: true
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: onyxdb-robot
subjects:
  - kind: ServiceAccount
    name: onyxdb-robot
roleRef:
  kind: Role
  name: onyxdb-robot
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: onyxdb
  labels:
    app.kubernetes.io/name: onyxdb
    app.kubernetes.io/instance: onyxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: onyxdb
      app.kubernetes.io/instance: onyxdb
  template:
    metadata:
      labels:
        app.kubernetes.io/name: onyxdb
        app.kubernetes.io/instance: onyxdb
    spec:
      serviceAccountName: onyxdb-robot
      containers:
        - name: onyxdb
          image: foxleren/onyxdb:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9001
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 9001
            initialDelaySeconds: 15
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 9001
            initialDelaySeconds: 15
            periodSeconds: 5
          envFrom:
            - secretRef:
                name: onyxdb
---
apiVersion: v1
kind: Service
metadata:
  name: onyxdb
  labels:
    app.kubernetes.io/name: onyxdb
    app.kubernetes.io/instance: onyxdb
spec:
  selector:
    app.kubernetes.io/name: onyxdb
    app.kubernetes.io/instance: onyxdb
  ports:
    - port: 9001
      targetPort: 9001
