default: 
  tags:
    - foxleren-ubuntu-gitlab-runner

services:
  - name: docker:dind
    # explicitly disable tls to avoid docker startup interruption
    command: ["--tls=false"]

variables:
  # Instruct Testcontainers to use the daemon of DinD, use port 2375 for non-tls connections.
  DOCKER_HOST: "tcp://docker:2375"
  # Instruct Docker not to start over TLS.
  DOCKER_TLS_CERTDIR: ""
  # Improve performance with overlayfs.
  DOCKER_DRIVER: overlay2

stages:
  - build

gradle-build:
  stage: build
  image: amazoncorretto:21-alpine
  script: ./gradlew clean build
  except:
    changes:
      - README.md
