apiVersion: psmdb.percona.com/v1
kind: PerconaServerMongoDB
metadata:
  creationTimestamp: '2025-04-25T11:25:57Z'
  generation: 1
  name: test-1-sandbox-mongo
  namespace: onyxdb
  resourceVersion: '435340'
  uid: b45c7a60-d2af-4d4b-b62a-2b873756e1e7
  selfLink: >-
    /apis/psmdb.percona.com/v1/namespaces/onyxdb/perconaservermongodbs/test-1-sandbox-mongo
status:
  conditions:
    - lastTransitionTime: '2025-04-25T11:25:58Z'
      status: 'False'
      type: sharding
    - lastTransitionTime: '2025-04-25T11:26:11Z'
      message: 'handleReplsetInit: no mongod containers in running state'
      reason: ErrorReconcile
      status: 'True'
      type: error
    - lastTransitionTime: '2025-04-25T11:26:38Z'
      status: 'True'
      type: initializing
    - lastTransitionTime: '2025-04-25T11:26:39Z'
      status: 'True'
      type: ready
  host: test-1-sandbox-mongo-rs0.onyxdb.svc.cluster.local
  mongoImage: percona/percona-server-mongodb:8.0.4-1-multi
  mongoVersion: 8.0.4-1
  observedGeneration: 1
  ready: 1
  replsets:
    rs0:
      initialized: true
      members:
        test-1-sandbox-mongo-rs0-0:
          name: >-
            test-1-sandbox-mongo-rs0-0.test-1-sandbox-mongo-rs0.onyxdb.svc.cluster.local:27017
          state: 1
          stateStr: PRIMARY
      ready: 1
      size: 1
      status: ready
  size: 1
  state: ready
spec:
  backup:
    enabled: true
    image: perconalab/percona-server-mongodb-operator:main-backup
    resources:
      limits:
        cpu: '0.3'
        memory: 1G
      requests:
        cpu: '0.3'
        memory: 1G
    storages:
      minio:
        s3:
          bucket: onyxdb
          credentialsSecret: minio-onyxdb
          endpointUrl: http://minio.minio.svc.cluster.local:30009
          region: us-east-1
        type: s3
    tasks:
      - enabled: true
        keep: 5
        name: backup
        schedule: 0 0 * * *
        storageName: minio
        type: logical
  crVersion: 1.19.1
  enableVolumeExpansion: false
  image: percona/percona-server-mongodb:8.0.4-1-multi
  imagePullPolicy: IfNotPresent
  replsets:
    - affinity:
        advanced:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: kubernetes.io/os
                      operator: In
                      values:
                        - linux
      configuration: |
        systemLog:
          path: /data/db/mongod.log
          destination: file
          logAppend: true
      name: rs0
      resources:
        limits:
          cpu: '0.3'
          memory: 0.5Gi
        requests:
          cpu: '0.3'
          memory: 0.5Gi
      sidecarVolumes:
        - configMap:
            name: test-1-sandbox-mongo-vector
          name: vector-config-volume
      sidecars:
        - args:
            - '--discovering-mode'
            - '--compatible-mode'
            - '--collect-all'
            - '--log.level=debug'
            - '--mongodb.uri=$(MONGODB_URI)'
          env:
            - name: EXPORTER_USER
              valueFrom:
                secretKeyRef:
                  key: MONGODB_DATABASE_ADMIN_USER
                  name: test-1-sandbox-mongo-users
            - name: EXPORTER_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MONGODB_DATABASE_ADMIN_PASSWORD
                  name: test-1-sandbox-mongo-users
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MONGODB_URI
              value: mongodb://$(EXPORTER_USER):$(EXPORTER_PASSWORD)@$(POD_IP):27017
          image: percona/mongodb_exporter:0.44
          name: exporter
        - args:
            - '--config=/etc/vector/vector.yaml'
          command:
            - vector
          image: timberio/vector:0.31.0-debian
          name: vector
          volumeMounts:
            - mountPath: /etc/vector
              name: vector-config-volume
            - mountPath: /data/db
              name: mongod-data
          workingDir: /data/db
      size: 1
      volumeSpec:
        persistentVolumeClaim:
          resources:
            requests:
              storage: 1Gi
  secrets:
    users: test-1-sandbox-mongo-users
  sharding:
    enabled: false
  unsafeFlags:
    replsetSize: true
  upgradeOptions:
    apply: disabled
