openapi: 3.0.0
info:
  version: 1.0.0
  title: onyxdb-api
servers:
  - url: http://localhost:8080
    description: localhost
paths:
  /api/v1/clusters:
    post:
      summary: Create cluster.
      operationId: v1ClustersCreateCluster
      tags:
        - v1Clusters
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/V1CreateClusterRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/V1CreateClusterResponse'

components:
  schemas:
    V1CreateClusterRequest:
      type: object
      required:
        - name
        - storage
        - dbSpec
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 64
        description:
          type: string
          minLength: 1
          maxLength: 256
        storage:
          type: object
          required:
            - diskSize
          properties:
            diskSize:
              type: integer
              format: int64
              description: Disk size in bytes.
              minimum: 1073741824 # 1Gb
              maximum: 10737418240 # 10 Gb
        dbSpec:
          type: object
          required:
            - type
          properties:
            type:
              type: string
              enum:
                - mongodb
                - postgresql
            mongodb:
              type: object
              required:
                - version
              properties:
                version:
                  type: string
                  enum:
                    - '6.0'
                    - '5.0'
                mongodbV6x0:
                  type: object
                  additionalProperties:
                    type: string
                mongodbV5x0:
                  type: object
                  additionalProperties:
                    type: string
    V1CreateClusterResponse:
      type: object
      required:
        - clusterId
      properties:
        clusterId:
          type: string
          format: uuid
