openapi: 3.0.0
info:
  version: 1.0.0
  title: onyx-api
servers:
  - url: http://localhost:8080
    description: localhost
paths:
  /api/v1/clusters:
    post:
      summary: Create cluster.
      operationId: apiV1CreateCluster
      tags:
        - onyxApiV1Clusters
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateClusterRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateClusterResponse'

components:
  schemas:
    CreateClusterRequest:
      type: object
      required:
        - name
        - type
      properties:
        name:
          type: string
        type:
          type: string
          enum:
            - mongo
    CreateClusterResponse:
      type: object
      required:
        - clusterId
      properties:
        clusterId:
          type: string
          format: uuid
