openapi: 3.0.0
info:
  version: 1.0.0
  title: onyxdb-mdb
servers:
  - url: http://localhost:9001
    description: localhost
paths:
  /api/v1/hardware-presets:
    get:
      summary: Get hardware presets
      operationId: listHardwarePresets
      tags:
        - v1HardwarePresets
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/V1ListHardwarePresetsResponse'
    post:
      summary: Create hardware preset
      operationId: createHardwarePreset
      tags:
        - v1HardwarePresets
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/V1CreateHardwarePresetRequest'
      responses:
        '200':
          description: OK
  /api/v1/hardware-presets/{hardwarePresetId}:
    get:
      summary: Get hardware preset
      operationId: getHardwarePreset
      tags:
        - v1HardwarePresets
      parameters:
        - $ref: '#/components/parameters/HardwarePresetIdPV'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/V1HardwarePresetResponse'
    put:
      summary: Update hardware preset
      operationId: updateHardwarePreset
      tags:
        - v1HardwarePresets
      parameters:
        - $ref: '#/components/parameters/HardwarePresetIdPV'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/V1UpdateHardwarePresetRequest'
      responses:
        '200':
          description: OK
    delete:
      summary: Delete hardware preset
      operationId: deleteHardwarePreset
      tags:
        - v1HardwarePresets
      parameters:
        - $ref: '#/components/parameters/HardwarePresetIdPV'
      responses:
        '200':
          description: OK
  /api/v1/zones:
    get:
      summary: Get zones
      operationId: listZones
      tags:
        - v1Zones
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/V1ListZonesResponse'
    post:
      summary: Create zone
      operationId: createZone
      tags:
        - v1Zones
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/V1CreateZoneRequest'
      responses:
        '200':
          description: OK
  /api/v1/zones/{zoneId}:
    get:
      summary: Get zone
      operationId: getZone
      tags:
        - v1Zones
      parameters:
        - $ref: '#/components/parameters/ZoneIdPV'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/V1ZoneResponse'
    put:
      summary: Update zone
      operationId: updateZone
      tags:
        - v1Zones
      parameters:
        - $ref: '#/components/parameters/ZoneIdPV'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/V1UpdateZoneRequest'
      responses:
        '200':
          description: OK
    delete:
      summary: Delete zone
      operationId: deleteZone
      tags:
        - v1Zones
      parameters:
        - $ref: '#/components/parameters/ZoneIdPV'
      responses:
        '200':
          description: OK
components:
  schemas:
    V1BadRequestResponse:
      type: object
      properties:
        message:
          type: string
      required:
        - message
    V1ListHardwarePresetsResponse:
      type: object
      properties:
        hardwarePresets:
          type: array
          items:
            $ref: '#/components/schemas/V1HardwarePresetResponse'
      required:
        - hardwarePresets
    V1HardwarePresetResponse:
      type: object
      properties:
        id:
          type: string
        type:
          $ref: '#/components/schemas/V1HardwarePresetType'
        vcpu:
          type: number
          format: double
        ram:
          type: integer
          format: int64
      required:
        - id
        - type
        - vcpu
        - ram
    V1CreateHardwarePresetRequest:
      type: object
      properties:
        id:
          type: string
        type:
          $ref: '#/components/schemas/V1HardwarePresetType'
        vcpu:
          type: number
          format: double
        ram:
          type: integer
          format: int64
      required:
        - id
        - type
        - vcpu
        - ram
    V1UpdateHardwarePresetRequest:
      type: object
      properties:
        type:
          $ref: '#/components/schemas/V1HardwarePresetType'
        vcpu:
          type: number
          format: double
        ram:
          type: integer
          format: int64
      required:
        - type
        - vcpu
        - ram
    V1HardwarePresetType:
      type: string
      enum:
        - cpu_optimized
        - standard
        - ram_optimized
    V1ListZonesResponse:
      type: object
      properties:
        zones:
          type: array
          items:
            $ref: '#/components/schemas/V1ZoneResponse'
      required:
        - zones
    V1ZoneResponse:
      type: object
      properties:
        id:
          type: string
        description:
          type: string
        selector:
          type: string
        isAvailable:
          type: boolean
      required:
        - id
        - description
        - selector
        - isAvailable
    V1CreateZoneRequest:
      type: object
      properties:
        id:
          type: string
        description:
          type: string
        selector:
          type: string
      required:
        - id
        - description
        - selector
    V1UpdateZoneRequest:
      type: object
      properties:
        description:
          type: string
        selector:
          type: string
        isAvailable:
          type: boolean
      required:
        - description
        - selector
        - isAvailable
  parameters:
    HardwarePresetIdPV:
      name: hardwarePresetId
      in: path
      required: true
      schema:
        type: string
    ZoneIdPV:
      name: zoneId
      in: path
      required: true
      schema:
        type: string
