openapi: 3.0.0
info:
  version: 1.0.0
  title: onyxdb-mdb
servers:
  - url: http://localhost:9001
    description: localhost
paths:
  /api/v1/hardware-presets:
    get:
      summary: Get hardware presets
      operationId: listHardwarePresets
      tags:
        - v1HardwarePresets
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/V1ListHardwarePresetsResponse'
    post:
      summary: Create hardware preset
      operationId: createHardwarePreset
      tags:
        - v1HardwarePresets
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/V1CreateHardwarePresetRequest'
      responses:
        '200':
          description: OK
  /api/v1/hardware-presets/{hardwarePresetId}:
    get:
      summary: Get hardware preset by id
      operationId: getHardwarePreset
      tags:
        - v1HardwarePresets
      parameters:
        - name: hardwarePresetId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/V1HardwarePresetResponse'
    put:
      summary: Update hardware preset by id
      operationId: updateHardwarePreset
      tags:
        - v1HardwarePresets
      parameters:
        - name: hardwarePresetId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/V1UpdateHardwarePresetRequest'
      responses:
        '200':
          description: OK
    delete:
      summary: Delete hardware preset by id
      operationId: deleteHardwarePreset
      tags:
        - v1HardwarePresets
      parameters:
        - name: hardwarePresetId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK

components:
  schemas:
    V1BadRequestResponse:
      type: object
      required:
        - message
      properties:
        message:
          type: string
    V1ListHardwarePresetsResponse:
      type: object
      properties:
        hardwarePresets:
          type: array
          items:
            $ref: '#/components/schemas/V1HardwarePresetResponse'
      required:
        - hardwarePresets
    V1HardwarePresetResponse:
      type: object
      properties:
        id:
          type: string
        type:
          $ref: '#/components/schemas/V1HardwarePresetType'
        vcpu:
          type: integer
          format: int64
        ram:
          type: integer
          format: int64
      required:
        - id
        - type
        - vcpu
        - ram
    V1CreateHardwarePresetRequest:
      type: object
      properties:
        id:
          type: string
        type:
          $ref: '#/components/schemas/V1HardwarePresetType'
        vcpu:
          type: integer
          format: int64
        ram:
          type: integer
          format: int64
    V1UpdateHardwarePresetRequest:
      type: object
      properties:
        type:
          $ref: '#/components/schemas/V1HardwarePresetType'
        vcpu:
          type: integer
          format: int64
        ram:
          type: integer
          format: int64
    V1HardwarePresetType:
      type: string
      enum:
        - cpu_optimized
        - standard
        - ram_optimized
