openapi: 3.0.0
info:
  version: 1.0.0
  title: onyxdb-mdb
servers:
  - url: http://localhost:9001
    description: localhost
paths:
  /api/v1/projects:
    post:
      summary: Create project
      operationId: v1ProjectsCreateProject
      tags:
        - v1Projects
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/V1CreateProjectRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/V1CreateProjectResponse'
  /api/v1/clusters:
    post:
      summary: Create cluster.
      operationId: v1ClustersCreateCluster
      tags:
        - v1Clusters
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/V1CreateClusterRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/V1CreateClusterResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/V1BadRequestResponse'
  /api/v1/clusters/{id}:
    get:
      summary: Get cluster by id.
      operationId: v1ClustersGetCluster
      tags:
        - v1Clusters
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/V1GetClusterResponse'
  /api/v1/clusters/update-project:
    put:
      summary: Update cluster project
      operationId: v1ClustersUpdateProject
      tags:
        - v1Clusters
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/V1UpdateClusterProjectRequest'
      responses:
        '200':
          description: OK
components:
  schemas:
    V1BadRequestResponse:
      type: object
      required:
        - message
      properties:
        message:
          type: string
    V1CreateProjectRequest:
      type: object
      required:
        - name
        - ownerId
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 64
          example: test-project
        ownerId:
          type: string
          format: uuid
    V1CreateProjectResponse:
      type: object
      required:
        - clusterId
      properties:
        clusterId:
          type: string
          format: uuid
    V1CreateClusterRequest:
      type: object
      required:
        - name
        - projectId
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 64
          example: test-cluster
        projectId:
          type: string
          format: uuid
    V1CreateClusterResponse:
      type: object
      required:
        - clusterId
      properties:
        clusterId:
          type: string
          format: uuid
    V1GetClusterResponse:
      type: object
      required:
        - id
        - name
        - projectId
        - type
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        projectId:
          type: string
          format: uuid
        type:
          type: string
          enum:
            - mongodb
    V1UpdateClusterProjectRequest:
      type: object
      required:
        - clusterId
        - projectId
      properties:
        clusterId:
          type: string
          format: uuid
        projectId:
          type: string
          format: uuid
