spring:
  application:
    name: onyxdb
  task:
    scheduling:
      pool:
        size: 5
  graphql:
    cors:
      allowed-methods=POST:
    graphiql:
      enabled: true
    schema:
      #      locations=classpath*:/:
      locations=classpath*:graphql/**/:

server:
  port: 9001

springdoc:
  swagger-ui:
    path: /swagger
  api-docs:
    path: /openapi

logging:
  level:
    org:
      jooq:
        Constants: off

onyxdb:
  base-url: http://host.minikube.internal:9001
  agent:
    base-url: http://localhost:9004
  postgres:
    url: jdbc:postgresql://localhost:5632/onyxdb
    username: username
    password: password
  redis:
    host: localhost
    port: 6379
  clickhouse:
    url: jdbc:clickhouse://localhost:8323/onyxdb
    username: username
    password: password
  flyway:
    postgres:
      location: db/migrations/postgres
    clickhouse:
      location: db/migrations/clickhouse
  victoria-logs:
    base-url: http://vls-victoria-logs-single-server.onyxdb.svc.cluster.local:9428
  tasks:
    collect-product-quota-usage:
      fixed-rate: PT15M
      lock-at-least-for: 14m
      lock-at-most-for: 14m
  workers:
    process-cluster-tasks:
      min-threads: 1
      max-threads: 5
      polling-interval-seconds: 1
  jwt-token:
    salt-jwt: ${JWT_TOKEN_SALT_JWT:ns9ozm2ani3oc6xo4pozoijxsperv8rpo1bsdijvdlpszq}
    salt-refresh: ${JWT_TOKEN_SALT_REFRESH:nn9ozm2ani3oc6xo4pozoijxsperv8rpo1bsdijvdlpszq}
    expiration: ${JWT_TOKEN_EXPIRATION:5 } # minutes
