spring:
  application:
    name: onyxdb
  task:
    scheduling:
      pool:
        size: 5

server:
  port: 9001

springdoc:
  api-docs:
    path: /internal/api-docs
  swagger-ui:
    path: /internal/swagger-ui

logging:
  level:
    org:
      jooq:
        Constants: off

onyxdb:
  base-url: http://host.minikube.internal:9001
  postgres:
    url: jdbc:postgresql://localhost/onyxdb
    username: postgres
    password: password
  redis:
    host: localhost
    port: 6379
  clickhouse:
    url: jdbc:clickhouse://localhost:8123/onyxdb
    username: ""
    password: ""
  victoria-logs:
    base-url: http://vls-victoria-logs-single-server.onyxdb.svc.cluster.local:9428
  tasks:
    collect-product-quota-usage:
      fixed-rate: PT5S
      lock-at-least-for: 5s
      lock-at-most-for: 5s

onyxdb-app:
  workers:
    process-cluster-tasks:
      min-threads: 1
      max-threads: 5
      polling-interval-seconds: 5
