spring:
  application:
    name: onyxdb
  task:
    scheduling:
      pool:
        size: 5

server:
  port: 9001

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui

logging:
  level:
    org:
      jooq:
        Constants: off

onyxdb:
  base-url: http://host.minikube.internal:9001
  agent:
    base-url: http://localhost:9004
  postgres:
    url: jdbc:postgresql://localhost:5432/onyxdb
    username: postgres
    password: password
  redis:
    host: localhost
    port: 6379
  clickhouse:
    url: jdbc:clickhouse://localhost:8123/onyxdb
    username: ""
    password: ""
  flyway:
    postgres:
      location: db/migrations/postgres
    clickhouse:
      location: db/migrations/clickhouse
  victoria-logs:
    base-url: http://vlogs-onyxdb.onyxdb.svc.cluster.local:9428
  tasks:
    collect-product-quota-usage:
      fixed-rate: PT1S
      lock-at-least-for: 1s
      lock-at-most-for: 1s

onyxdb-app:
  workers:
    process-cluster-tasks:
      min-threads: 1
      max-threads: 5
      polling-interval-seconds: 1
