spring:
  application:
    name: onyxdb
  profiles:
    default: prod
  task:
    scheduling:
      pool:
        size: 5
  graphql:
    cors:
      allowed-methods=POST:
    graphiql:
      enabled: true
    schema:
      #      locations=classpath*:/:
      locations=classpath*:graphql/**/:

server:
  port: 9001

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /api-docs

logging:
  level:
    org:
      jooq:
        Constants: off

onyxdb:
  mdb:
    self-url: ${ONYXDB_SELF_URL:http://host.minikube.internal:9001 }
    self-namespace: ${ONYXDB_SELF_NAMESPACE:onyxdb}
    namespaces: ${ONYXDB_NAMESPACES:onyxdb}
    storage-classes: ${ONYXDB_STORAGE_CLASSES:standard}
    disabled-kube: false
  postgres:
    url: ${ONYXDB_POSTGRES_URL:jdbc:postgresql://localhost:5632/onyxdb}
    username: ${ONYXDB_POSTGRES_USER:username}
    password: ${ONYXDB_POSTGRES_PASSWORD:password}
  redis:
    host: ${ONYXDB_REDIS_HOST:localhost}
    port: ${ONYXDB_REDIS_PORT:6379}
    user: ${ONYXDB_REDIS_PORT:default}
    password: ${ONYXDB_REDIS_PORT:qwerty}
  clickhouse:
    url: ${ONYXDB_CLICKHOUSE_URL:jdbc:clickhouse://localhost:8323/onyxdb}
    username: ${ONYXDB_CLICKHOUSE_USER:username}
    password: ${ONYXDB_CLICKHOUSE_PASSWORD:password}
  minio:
    url: ${ONYXDB_MINIO_URL:http://minio.onyxdb.svc.cluster.local:9000}
    secret: ${ONYXDB_MINIO_SECRET:minio-onyxdb}
    bucket: ${ONYXDB_MINIO_BUCKET:onyxdb}
  victoria-logs:
    base-url: ${ONYXDB_VLOGS_URL:http://vls-victoria-logs-single-server.onyxdb.svc.cluster.local:9428}
  flyway:
    postgres:
      location: db/migrations/postgres
    clickhouse:
      location: db/migrations/clickhouse
  tasks:
    collect-product-quota-usage:
      fixed-rate: PT15M
      lock-at-least-for: 14m
      lock-at-most-for: 14m
  workers:
    process-cluster-tasks:
      min-threads: 1
      max-threads: 5
      polling-interval-seconds: 1
  jwt-token:
    salt-jwt: ${JWT_TOKEN_SALT_JWT:ns9ozm2ani3oc6xo4pozoijxsperv8rpo1bsdijvdlpszq}
    salt-refresh: ${JWT_TOKEN_SALT_REFRESH:nn9ozm2ani3oc6xo4pozoijxsperv8rpo1bsdijvdlpszq}
    expiration: ${JWT_TOKEN_EXPIRATION:5 } # minutes
