spring:
  application:
    name: onyxdb
  task:
    scheduling:
      pool:
        size: 5

server:
  port: 9001

springdoc:
  api-docs:
    path: /internal/api-docs
  swagger-ui:
    path: /internal/swagger-ui

logging:
  level:
    org:
      jooq:
        Constants: off

onyxdb:
  base-url: http://host.minikube.internal:9001
  postgres:
    url: jdbc:postgresql://localhost/onyxdb
    username: username
    password: password
  redis:
    host: localhost
    port: 6379
  clickhouse:
    url: jdbc:clickhouse://localhost:8123/onyxdb
    username: username
    password: password
  tasks:
    collect-product-quota-usage:
      fixed-rate: PT15M
      lock-at-least-for: 14m
      lock-at-most-for: 14m

onyxdb-app:
  workers:
    process-cluster-tasks:
      min-threads: 1
      max-threads: 5
      polling-interval-seconds: 5
  victoria-logs:
    base-url: http://vlogs-demo.onyxdb.svc.cluster.local:9428
