spring:
  application:
    name: onyxdb-mdb
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${ONYXDB_MDB_PSQL_URL:jdbc:postgresql://localhost:5432/onyxdb}
    username: ${ONYXDB_MDB_PSQL_USERNAME:postgres}
    password: ${ONYXDB_MDB_PSQL_PASSWORD:password}
    hikari:
      auto-commit: true
      transaction-isolation: TRANSACTION_READ_COMMITTED
  jooq:
    sql-dialect: Postgres
  flyway:
    url: ${ONYXDB_MDB_PSQL_URL:jdbc:postgresql://localhost:5432/onyxdb}
    username: ${ONYXDB_MDB_PSQL_USERNAME:postgres}
    password: ${ONYXDB_MDB_PSQL_PASSWORD:password}
    locations: classpath:db/migration
    enabled: true
server:
  port: ${ONYXDB_MDB_HTTP_PORT:9001}

springdoc:
  api-docs:
    path: /internal/api-docs
  swagger-ui:
    path: /internal/swagger-ui

logging:
  level:
    org:
      jooq:
        Constants: off

onyxdb:
  base-url: http://host.minikube.internal:9001
  redis:
    host: localhost
    port: 6379
  clickhouse:
    url: jdbc:clickhouse://localhost:8123/onyxdb

onyxdb-app:
  workers:
    process-cluster-tasks:
      min-threads: 1
      max-threads: 5
      polling-interval-seconds: 5
  victoria-logs:
    base-url: http://vlogs-demo.onyxdb.svc.cluster.local:9428
