spring:
  application:
    name: onyxdb-idm
  graphql:
    cors:
      allowed-methods=POST:
    graphiql:
      enabled: true
    schema:
#      locations=classpath*:/:
      locations=classpath*:graphql/**/:

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${ONYXDB_IDM_API_PSQL_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${ONYXDB_IDM_API_PSQL_USERNAME:ao.fedorov}
    password: ${ONYXDB_IDM_API_PSQL_PASSWORD:root}
  jooq:
    sql-dialect: Postgres
  flyway:
    enabled: true

#logging:
#  level:
#    root: INFO
#
#server:
#  port: ${ONYXDB_IDM_API_HTTP_PORT:9002}
#
#springdoc:
#  api-docs:
#    path: /internal/api-docs
#  swagger-ui:
#    path: /internal/swagger-ui
