spring:
  application:
    name: onyxdb-idm
  graphql:
    cors:
      allowed-methods=POST:
    graphiql:
      enabled: true
    schema:
      #      locations=classpath*:/:
      locations=classpath*:graphql/**/:

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${ONYXDB_IDM_API_PSQL_URL:jdbc:postgresql://localhost:5432/ao.fedorov}
    username: ${ONYXDB_IDM_API_PSQL_USERNAME:ao.fedorov}
    password: ${ONYXDB_IDM_API_PSQL_PASSWORD:}

  jooq:
    sql-dialect: Postgres

  redis:
    host: localhost
    port: 6379

  flyway:
    url: ${ONYXDB_IDM_API_PSQL_URL:jdbc:postgresql://localhost:5432/ao.fedorov}
    username: ${ONYXDB_IDM_API_PSQL_USERNAME:ao.fedorov}
    password: ${ONYXDB_IDM_API_PSQL_PASSWORD:}
    locations: classpath:db/migration
    enabled: true

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter:
      DEBUG

server:
  port: ${ONYXDB_IDM_API_HTTP_PORT:9003}

springdoc:
  api-docs:
    path: /internal/api-docs
  swagger-ui:
    path: /internal/swagger-ui

jwt-token:
  salt-jwt: ${JWT_TOKEN_SALT_JWT:ns9ozm2ani3oc6xo4pozoijxsperv8rpo1bsdijvdlpszq}
  salt-refresh: ${JWT_TOKEN_SALT_REFRESH:nn9ozm2ani3oc6xo4pozoijxsperv8rpo1bsdijvdlpszq}
  expiration: ${JWT_TOKEN_EXPIRATION:5 } # minutes