[versions]
springBoot = "3.3.5"
openapiGenerator = "7.5.0"
swaggerCoreV3-swaggerAnnotations = "2.2.20"
javaxAnnotation-annotionApi = "1.3.2"
javaxValidation-validationApi = "2.0.0.Final"
lombok-gradlePlugin = "8.10.2"

[plugins]
springBoot = { id = "org.springframework.boot" }
openapiGenerator = { id = "org.openapi.generator", version.ref = "openapiGenerator" }
lombok = { id = "io.freefair.lombok",  version.ref = "lombok-gradlePlugin" }

[libraries]
springBoot-gradlePlugin = { group = "org.springframework.boot", name = "spring-boot-gradle-plugin", version.ref = "springBoot" }
springBoot-starterWeb = { group = "org.springframework.boot", name = "spring-boot-starter-web", version.ref = "springBoot" }
springBoot-starterLog4j2 = { group = "org.springframework.boot", name = "spring-boot-starter-log4j2", version.ref = "springBoot" }
springBoot-starterTest = { group = "org.springframework.boot", name = "spring-boot-starter-test", version.ref = "springBoot" }
swaggerCoreV3-swaggerAnnotations = { group = "io.swagger.core.v3", name = "swagger-annotations", version.ref = "swaggerCoreV3-swaggerAnnotations" }
javaxAnnotation-annotionApi = { group = "javax.annotation", name = "javax.annotation-api", version.ref = "javaxAnnotation-annotionApi" }
javaxValidation-validationApi = { group = "javax.validation", name = "validation-api", version.ref = "javaxValidation-validationApi" }
