apiVersion: v1
kind: ConfigMap
metadata:
  namespace: onyxdb
  name: sidecar-vector-config
data:
  vector.yaml: |
    sources:
      mongod_logs:
        type: file
        include:
          - "/data/db/mongod.log" 
    
    transforms:
      enriched_mongod_logs:
        type: remap
        inputs:
          - mongod_logs
        source: |-
          .onyxdb_project = "some-project"
          .onyxdb_cluster = "some-cluster"

    sinks:
      vlogs:
        inputs:
          - enriched_mongod_logs
        type: http
        uri: http://vlogs-demo.onyxdb.svc.cluster.local:9428/insert/jsonline?_stream_fields=host,container_name&_msg_field=message&_time_field=timestamp
        compression: gzip
        encoding:
          codec: json
        framing:
          method: newline_delimited
        healthcheck:
          enabled: false
