apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: demo-cluster-metrics-service-scrape
#  labels:
  namespace: onyxdb
spec:
  endpoints:
    - port: http-metrics
  selector:
    matchLabels:
      app: demo-cluster-metrics
