apiVersion: operator.victoriametrics.com/v1beta1
kind: VLogs
metadata:
  name: onyxdb
spec:
  image:
    repository: victoriametrics/victoria-logs
    tag: v1.21.0-victorialogs
    pullPolicy: Always
  retentionPeriod: "24h"
  removePvcAfterDelete: true
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
