apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: onyxdb
spec:
  replicaCount: 1
  image:
    repository: victoriametrics/vmagent
    tag: v1.93.4
    pullPolicy: Always
  remoteWrite:
    - url: "http://vminsert-onyxdb.onyxdb.svc.cluster.local:8480/insert/0/prometheus/api/v1/write"
  serviceScrapeNamespaceSelector: {}
  podScrapeNamespaceSelector: {}
  podScrapeSelector: {}
  serviceScrapeSelector: {}
  nodeScrapeSelector: {}
  nodeScrapeNamespaceSelector: {}
  staticScrapeSelector: {}
  staticScrapeNamespaceSelector: {}
