apiVersion: operator.victoriametrics.com/v1beta1
kind: VMCluster
metadata:
  name: onyxdb
  namespace: onyxdb
spec:
  retentionPeriod: "24h"
  vmstorage:
    replicaCount: 1
  vmselect:
    replicaCount: 1
  vminsert:
    replicaCount: 1
