apiVersion: v1
kind: ConfigMap
metadata:
  name: [[${metadata_name}]]
data:
  vector.yaml: |
    sources:
      mongod_logs:
        type: file
        include:
          - "/data/db/mongod.log"
    
    transforms:
      enriched_mongod_logs:
        type: remap
        inputs:
          - mongod_logs
        source: |-
          .onyxdb_project = [[${onyxdb_project}]]
          .onyxdb_cluster = [[${onyxdb_cluster}]]

    sinks:
      vlogs:
        inputs:
          - enriched_mongod_logs
        type: http
        uri: [[${vlogs_url}]]/insert/jsonline?_stream_fields=host,container_name&_msg_field=message&_time_field=timestamp
        compression: gzip
        encoding:
          codec: json
        framing:
          method: newline_delimited
        healthcheck:
          enabled: true
