apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: managed-mongodb-stateful-set
  namespace: onyxdb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: managed-mongodb
      managedBy: mongodb-operator
  serviceName: managed-mongodb
#  serviceName: onyxdb-managed-mongodb
  template:
    metadata:
      name: managed-mongodb
      namespace: onyxdb
      labels:
        app: managed-mongodb
        managedBy: mongodb-operator
    spec:
      containers:
        - name: managed-mongodb
          image: mongo:7.0.16
          imagePullPolicy: IfNotPresent
          command:
            - mongod
            - '--bind_ip_all'
            - '--dbpath'
            - /data/db
            - '--replSet'
            - rs0
          resources:
            limits:
              memory: 1Gi
          volumeMounts:
            - mountPath: /data/db
              name: managed-mongodb-pvc
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  key: user
                  name: onyxdb-managed-mongodb-secret
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: onyxdb-managed-mongodb-secret
  volumeClaimTemplates:
    - metadata:
        name: managed-mongodb-pvc
        namespace: onyxdb
      spec:
        storageClassName: 'standard'
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
