apiVersion: v1
kind: Service
metadata:
  name: managed-mongodb
  namespace: onyxdb
  labels:
    app: managed-mongodb
    managedBy: mongodb-operator
spec:
  selector:
    app: managed-mongodb
    managedBy: mongodb-operator
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
