apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: onyxdb-managed-mongodb-stateful-set
  namespace: onyxdb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: onyxdb-managed-mongodb
      managedBy: onyxdb
  serviceName: onyxdb-managed-mongodb
  template:
    metadata:
      namespace: onyxdb
      labels:
        app: onyxdb-managed-mongodb
        managedBy: onyxdb
    spec:
      containers:
        - name: onyxdb-managed-mongodb
          image: mongo:7.0.16
          imagePullPolicy: IfNotPresent
          command:
            - mongod
            - '--bind_ip_all'
            - '--dbpath'
            - /data/db
            - '--replSet'
            - rs0
          volumeMounts:
            - mountPath: /data/db
              name: onyxdb-managed-mongodb-pvc
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  key: user
                  name: onyxdb-managed-mongodb-secret
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: onyxdb-managed-mongodb-secret
  volumeClaimTemplates:
    - metadata:
        name: onyxdb-managed-mongodb-pvc
      spec:
        storageClassName: 'standard'
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
