apiVersion: v1
kind: Service
metadata:
  name: managed-mongodb
  namespace: onyxdb
  labels:
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: test
    app.kubernetes.io/managed-by: onyxdb-managed-mongodb-operator
    app.kubernetes.io/name: onyxdb-managed-mongodb
    app.kubernetes.io/part-of: onyxdb-managed-mongodb
spec:
  selector:
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: test
    app.kubernetes.io/managed-by: onyxdb-managed-mongodb-operator
    app.kubernetes.io/name: onyxdb-managed-mongodb
    app.kubernetes.io/part-of: onyxdb-managed-mongodb
  clusterIP: None
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
