apiVersion: psmdb.percona.com/v1
kind: PerconaServerMongoDBBackup
metadata:
  creationTimestamp: '2025-05-09T21:19:00Z'
  finalizers:
    - percona.com/delete-backup
  generateName: cron-test-1-sandbox-m-20250509211900-
  generation: 1
  labels:
    app.kubernetes.io/instance: test-1-sandbox-mongo
    app.kubernetes.io/managed-by: percona-server-mongodb-operator
    app.kubernetes.io/name: percona-server-mongodb
    app.kubernetes.io/part-of: percona-server-mongodb
    percona.com/backup-ancestor: backup
    percona.com/backup-type: cron
    percona.com/cluster: test-1-sandbox-mongo
  name: cron-test-1-sandbox-m-20250509211900-2cvd9
  namespace: onyxdb
  resourceVersion: '699686'
  uid: 18cf1aaa-4850-4deb-89aa-b18588dcb870
  selfLink: >-
    /apis/psmdb.percona.com/v1/namespaces/onyxdb/perconaservermongodbbackups/cron-test-1-sandbox-m-20250509211900-2cvd9
status:
  destination: s3://onyxdb/mongodb/sandbox/test-1/2025-05-09T21:19:21Z
  lastTransition: '2025-05-09T21:19:25Z'
  pbmName: '2025-05-09T21:19:21Z'
  pbmPod: >-
    test-1-sandbox-mongo-rs0-0.test-1-sandbox-mongo-rs0.onyxdb.svc.cluster.local:27017
  pbmPods:
    rs0: >-
      test-1-sandbox-mongo-rs0-0.test-1-sandbox-mongo-rs0.onyxdb.svc.cluster.local:27017
  replsetNames:
    - rs0
  s3:
    bucket: onyxdb
    credentialsSecret: minio-onyxdb
    endpointUrl: http://minio.onyxdb.svc.cluster.local:9000
    prefix: mongodb/sandbox/test-1
    region: us-east-1
    serverSideEncryption: {}
  start: '2025-05-09T21:19:21Z'
  state: running
  storageName: minio
  type: logical
spec:
  clusterName: test-1-sandbox-mongo
  compressionType: gzip
  storageName: minio
  type: logical
