spring:
  application:
    name: onyxdb-mdb
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${ONYXDB_MDB_PSQL_URL:jdbc:postgresql://localhost:5432/dev}
    username: ${ONYXDB_MDB_PSQL_USERNAME:postgres}
    password: ${ONYXDB_MDB_PSQL_PASSWORD:qwerty}
  jooq:
    sql-dialect: Postgres
  flyway:
    enabled: true
  task:
    scheduling:
      pool:
        size: 2
#    execution:
#      pool:
#        core-size: 5
server:
  port: ${ONYXDB_MDB_HTTP_PORT:9001}

springdoc:
  api-docs:
    path: /internal/api-docs
  swagger-ui:
    path: /internal/swagger-ui

onyxdb-app:
  tasks:
    process-cluster-operations:
#      executor:
#        core-pool-size: 1
#        max-pool-size: 3
#        queue-capacity: 0
      initial-delay-string: PT0S
      fixed-rate-string: PT01S
