apiVersion: operator.victoriametrics.com/v1beta1
kind: VLogs
metadata:
  name: onyxdb
  namespace: onyxdb-vm
spec:
#  image:
#    repository: victoriametrics/victoria-logs
#    tag: v1.4.0
#    pullPolicy: Always
  retentionPeriod: "24h"
  removePvcAfterDelete: true
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
#  resources:
#    requests:
#      memory: 500Mi
#      cpu: 500m
#    limits:
#      memory: 10Gi
#      cpu: 5
