apiVersion: v1
kind: ConfigMap
metadata:
  name: test-1-sandbox-mongo-logrotate
data:
  logrotate-mongod.conf: |
    /var/log/mongodb/mongod.log {
      daily
      size 100M
      rotate 10
      missingok
      compress
      delaycompress
      notifempty
      create 640 mongod mongod
      sharedscripts
      postrotate
      /bin/kill -SIGUSR1 `cat /var/run/mongodb/mongod.pid 2>/dev/null` >/dev/null 2>&1
      endscript
    }
