apiVersion: v1
kind: ConfigMap
metadata:
  name: mongod-logrotate
data:
  mongod.conf: |
    /data/db/mongod.log {
      su
      rotate 7
      daily
      size 1M
      missingok
      create 640 mongodb root
      delaycompress
      compress
      sharedscripts
      postrotate
       /bin/kill -SIGUSR1 $(cat /data/db/mongod.pid)
      endscript
    }
