apiVersion: psmdb.percona.com/v1
kind: PerconaServerMongoDB
metadata:
  finalizers:
    - percona.com/delete-psmdb-pvc
  name: mokhov-kt4-sandbox-mongo
  namespace: onyxdb
spec:
  crVersion: 1.19.1
  enableVolumeExpansion: false
  image: perconalab/percona-server-mongodb-operator:main-mongod8.0
  imagePullPolicy: IfNotPresent
  replsets:
    - affinity:
        advanced:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: kubernetes.io/os
                      operator: In
                      values:
                        - linux
      name: rs0
      resources:
        limits:
          cpu: '0.5'
          memory: 0.5Gi
        requests:
          cpu: '0.5'
          memory: 0.5Gi
      sidecarVolumes:
        - configMap:
            name: mokhov-kt4-sandbox-mongo-vector
          name: vector-config-volume
      sidecars:
        - args:
            - '--discovering-mode'
            - '--compatible-mode'
            - '--collect-all'
            - '--log.level=debug'
            - '--mongodb.uri=$(MONGODB_URI)'
          env:
            - name: EXPORTER_USER
              valueFrom:
                secretKeyRef:
                  key: MONGODB_DATABASE_ADMIN_USER
                  name: mokhov-kt4-sandbox-mongo-users
            - name: EXPORTER_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MONGODB_DATABASE_ADMIN_PASSWORD
                  name: mokhov-kt4-sandbox-mongo-users
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MONGODB_URI
              value: mongodb://$(EXPORTER_USER):$(EXPORTER_PASSWORD)@$(POD_IP):27017
          image: percona/mongodb_exporter:0.44
          name: exporter
        - args:
            - '--config=/etc/vector/vector.yaml'
          command:
            - vector
          image: timberio/vector:0.31.0-debian
          name: vector
          volumeMounts:
            - mountPath: /etc/vector
              name: vector-config-volume
            - mountPath: /data/db
              name: mongod-data
          workingDir: /data/db
      size: 3
      volumeSpec:
        persistentVolumeClaim:
          resources:
            requests:
              storage: 1Gi
  secrets:
    users: mokhov-kt4-sandbox-mongo-users
  sharding:
    enabled: false
  unsafeFlags:
    replsetSize: true
  upgradeOptions:
    apply: disabled
