{
 "title": "MongoDB metrics",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "project",
    "query": {
     "query": "label_values(mongodb_up,onyxdb_project)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(mongodb_up{onyxdb_project=~\"$project\"},onyxdb_cluster)"
    }
   },
   {
    "name": "hidden_host",
    "label": "hidden_host",
    "query": {
     "query": "label_values(mongodb_up{mongo_group=\"hidden\", mongodb_cluster_name=\"$cluster\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Availability of $cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Host available for write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max(mongodb_ss_repl_isWritablePrimary{onyxdb_cluster=~\"$cluster\", instance!=\"$hidden_host\"}) by (pod) == 1",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Hosts available for read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(mongodb_members_health{member_state=\"SECONDARY\", onyxdb_cluster=~\"$cluster\", instance!=\"$hidden_host\"}) by (pod) != 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Query Metrics for $cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }, "repeat": "env" },
  {
   "title": "Query on primary",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(mongodb_ss_opcounters{rs_state=\"1\", onyxdb_cluster=~\"$cluster\", instance!=\"$hidden_host\"})) by (legacy_op_type)",
     "legendFormat": "{{ legacy_op_type }}"
    }
   ]
  },
  {
   "title": "Queries on secondary",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(mongodb_ss_opcounters{rs_state=\"2\", onyxdb_cluster=~\"$cluster\", instance!=\"$hidden_host\"})) by (legacy_op_type)",
     "legendFormat": "{{legacy_op_type}}"
    }
   ]
  },
  {
   "title": "Replica queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(mongodb_ss_opcountersRepl{rs_state=\"2\", onyxdb_cluster=~\"$cluster\", instance!=\"$hidden_host\"})) by (legacy_op_type)",
     "legendFormat": "{{legacy_op_time}}"
    }
   ]
  },
  {
   "title": "Average operations time on cluster",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate((sum(mongodb_ss_opLatencies_latency{op_type=\"commands\", onyxdb_cluster=~\"$cluster\", instance!=\"$hidden_host\"}))) / rate((sum(mongodb_ss_opLatencies_ops{op_type=\"commands\", onyxdb_cluster=~\"$cluster\", instance!=\"$hidden_host\"})))",
     "legendFormat": "commands"
    },
    {
     "expr": "rate((sum(mongodb_ss_opLatencies_latency{op_type=\"reads\", onyxdb_cluster=~\"$cluster\"}))) / rate((sum(mongodb_ss_opLatencies_ops{op_type=\"reads\", onyxdb_cluster=~\"$cluster\"})))",
     "legendFormat": "reads"
    },
    {
     "expr": "rate((sum(mongodb_ss_opLatencies_latency{op_type=\"writes\", onyxdb_cluster=~\"$cluster\"}))) / rate((sum(mongodb_ss_opLatencies_ops{op_type=\"writes\", onyxdb_cluster=~\"$cluster\"})))",
     "legendFormat": "writes"
    },
    {
     "expr": "rate((sum(mongodb_ss_metrics_getLastError_wtime_totalMillis{onyxdb_cluster=~\"$cluster\"}))) / rate((sum(mongodb_ss_opLatencies_ops{op_type=\"writes\", onyxdb_cluster=~\"$cluster\"})))",
     "legendFormat": "writes_concern_wait"
    }
   ]
  },
  {
   "title": "Average operation time per host",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "(rate(sum(mongodb_ss_opLatencies_latency{onyxdb_cluster=~\"$cluster\", instance!=\"$hidden_host\"})by (pod))) / (rate(sum(mongodb_ss_opLatencies_ops{onyxdb_cluster=~\"$cluster\", instance!=\"$hidden_host\"})by (pod)))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Operation Metrics $cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 }, "repeat": "env" },
  {
   "title": "Total operations time on cluster",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(mongodb_ss_opLatencies_latency{onyxdb_cluster=~\"$cluster\", instance!=\"$hidden_host\"}) / 1000) by (op_type)",
     "legendFormat": "{{op_type}}"
    }
   ]
  },
  {
   "title": "Total operations count on cluster",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(mongodb_ss_opLatencies_ops{onyxdb_cluster=~\"$cluster\", instance!=\"$hidden_host\"})) by (op_type)",
     "legendFormat": "{{op_type}}"
    }
   ]
  },
  {
   "title": "Connections per host",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(mongodb_ss_connections{onyxdb_cluster=~\"$cluster\", conn_type=\"current\", instance!=\"$hidden_host\"}) by (pod)",
     "legendFormat": "{{op_type}}"
    },
    {
     "expr": "avg(mongodb_ss_connections{mongodb_cluster_name=~\"$cluster\", conn_type=\"current\", instance!=\"$hidden_host\"}) + avg(mongodb_ss_connections{mongodb_cluster_name=~\"$cluster\", conn_type=\"available\", instance!=\"$hidden_host\"})",
     "legendFormat": "max-connections"
    }
   ]
  },
  { "title": "Documents metrics for $cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 }, "repeat": "env" },
  {
   "title": "Documents affected on primary",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "rate(sum(mongodb_ss_metrics_document{onyxdb_cluster=~\"$cluster\", doc_op_type=\"deleted\", rs_state=\"1\", instance!=\"$hidden_host\"}) by (onyxdb_cluster))",
     "legendFormat": "deleted"
    },
    {
     "expr": "rate(sum(mongodb_ss_metrics_document{onyxdb_cluster=~\"$cluster\", doc_op_type=\"inserted\", rs_state=\"1\"}) by (onyxdb_cluster))",
     "legendFormat": "inserted"
    },
    {
     "expr": "rate(sum(mongodb_ss_metrics_document{onyxdb_cluster=~\"$cluster\", doc_op_type=\"updated\", rs_state=\"1\"}) by (onyxdb_cluster))",
     "legendFormat": "updated"
    },
    {
     "expr": "rate(sum(mongodb_ss_metrics_document{onyxdb_cluster=~\"$cluster\", doc_op_type=\"returned\", rs_state=\"1\"}) by (onyxdb_cluster))",
     "legendFormat": "returned"
    }
   ]
  },
  {
   "title": "Documents affected on secondary",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 35 },
   "targets": [
    {
     "expr": "rate(sum(mongodb_ss_metrics_document{onyxdb_cluster=~\"$cluster\", doc_op_type=\"deleted\", rs_state=\"2\", instance!=\"$hidden_host\"}) by (onyxdb_cluster))",
     "legendFormat": "deleted"
    },
    {
     "expr": "rate(sum(mongodb_ss_metrics_document{onyxdb_cluster=~\"$cluster\", doc_op_type=\"inserted\", rs_state=\"2\"}) by (onyxdb_cluster))",
     "legendFormat": "inserted"
    },
    {
     "expr": "rate(sum(mongodb_ss_metrics_document{onyxdb_cluster=~\"$cluster\", doc_op_type=\"updated\", rs_state=\"2\"}) by (onyxdb_cluster))",
     "legendFormat": "updated"
    },
    {
     "expr": "rate(sum(mongodb_ss_metrics_document{onyxdb_cluster=~\"$cluster\", doc_op_type=\"returned\", rs_state=\"2\"}) by (onyxdb_cluster))",
     "legendFormat": "returned"
    }
   ]
  },
  {
   "title": "Documents affected per host",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 35 },
   "targets": [
    {
     "expr": "rate(sum(mongodb_ss_metrics_document{onyxdb_cluster=~\"$cluster\", instance!=\"$hidden_host\"}) by (pod))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Scanned / Returned",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "sum(mongodb_ss_metrics_queryExecutor_scanned{onyxdb_cluster=~\"$cluster\", instance!=\"$hidden_host\"}) / sum(mongodb_ss_metrics_document{onyxdb_cluster=~\"$cluster\", doc_op_type=\"returned\", instance!=\"$hidden_host\"})",
     "legendFormat": "scanned_keys / returned_docs"
    },
    {
     "expr": "sum(mongodb_ss_metrics_queryExecutor_scannedObjects{onyxdb_cluster=~\"$cluster\"}) / sum(mongodb_ss_metrics_document{onyxdb_cluster=~\"$cluster\", doc_op_type=\"returned\"})",
     "legendFormat": "scanned_docs / returned_docs"
    }
   ]
  },
  {
   "title": "Replication lag per host and write_concern wait",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avg(rate(mongodb_ss_flowControl_isLaggedTimeMicros{onyxdb_cluster=~\"$cluster\", instance!=\"$hidden_host\"})) by (pod)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum((rate(mongodb_ss_metrics_getLastError_wtime_totalMillis{mongodb_cluster_name=~\"$cluster\", instance!=\"$hidden_host\"}))) / sum((rate(mongodb_ss_opLatencies_ops{op_type=\"writes\", mongodb_cluster_name=~\"$cluster\", instance!=\"$hidden_host\"})))",
     "legendFormat": "writes_concern_wait"
    }
   ]
  },
  {
   "title": "Page faults per host (sum)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(mongodb_ss_extra_info_page_faults{onyxdb_cluster=~\"$cluster\", instance!=\"$hidden_host\"})) by (onyxdb_cluster)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Open cursors total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(mongodb_ss_metrics_cursor_open{onyxdb_cluster=~\"$cluster\"}) by (csr_type)",
     "legendFormat": "{{csr_type}}"
    }
   ]
  },
  {
   "title": "TTL indexes activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(sum(mongodb_ss_metrics_ttl_deletedDocuments{onyxdb_cluster=~\"$cluster\"}))",
     "legendFormat": "mongodb_ss_metrics_ttl_deletedDocuments"
    },
    {
     "expr": "rate(sum(mongodb_ss_metrics_ttl_passes{mongodb_cluster_name=~\"$cluster\"}))",
     "legendFormat": "mongodb_ss_metrics_ttl_passes"
    }
   ]
  },
  {
   "title": "Page faults per host (rate per s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(mongodb_ss_extra_info_page_faults{onyxdb_cluster=~\"$cluster\", instance!=\"$hidden_host\"}[1s])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Write conflicts per host",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(sum(mongodb_ss_metrics_operation_writeConflicts{onyxdb_cluster=~\"$cluster\", instance!=\"$hidden_host\"}) by (pod))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scan and order per host",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(sum(mongodb_ss_metrics_operation_scanAndOrder{onyxdb_cluster=~\"$cluster\", instance!=\"$hidden_host\"}) by (pod))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Asserts total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(sum(mongodb_ss_asserts{onyxdb_cluster=~\"$cluster\"}) by (assert_type))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Readers/writers active queue per host",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(sum(mongodb_ss_globalLock_currentQueue{onyxdb_cluster=~\"$cluster\", count_type=\"writers\", instance!=\"$hidden_host\"}) by (pod))",
     "legendFormat": "{{instance}}_writers"
    },
    {
     "expr": "rate(sum(mongodb_ss_globalLock_currentQueue{mongodb_cluster_name=~\"$cluster\", count_type=\"readers\", instance!=\"$hidden_host\"}) by (instance))",
     "legendFormat": "{{instance}}_readres"
    }
   ]
  },
  { "title": "Data Metrics for $cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "Data size on primary",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(mongodb_dbstats_dataSize{onyxdb_cluster=~\"$cluster\", rs_state=\"1\"}) by (database) != 0",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Index size on primary",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(mongodb_dbstats_indexSize{onyxdb_cluster=~\"$cluster\", rs_state=\"1\"}) by (database) != 0",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Configured oplog size per host",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(mongodb_oplog_stats_maxSize{onyxdb_cluster=~\"$cluster\", instance!=\"$hidden_host\"}) by (pod) != 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Write operations time, top 5",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "rate(topk(5, avg(mongodb_top_writeLock_time{onyxdb_cluster=~\"$cluster\"}) by (database, collection)))",
     "legendFormat": "{{database}}.{{collection}}"
    }
   ]
  },
  {
   "title": "Write operations time, top 5",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "rate(topk(5, avg(mongodb_top_writeLock_time{onyxdb_cluster=~\"$cluster\"}) by (database, collection)))",
     "legendFormat": "{{database}}.{{collection}}"
    }
   ]
  },
  {
   "title": "Oplog window",
   "type": "timeseries",
   "description": "Capacity of oplog window on the replica",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "targets": [
    {
     "expr": "(mongodb_mongod_replset_oplog_head_timestamp{onyxdb_cluster=\"$cluster\", instance!=\"$hidden_host\"} - mongodb_mongod_replset_oplog_tail_timestamp{ onyxdb_cluster=\"$cluster\", instance!=\"$hidden_host\"}) / (3600 * 24)"
    }
   ]
  },
  {
   "title": "Resource Metrics for $cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk space usage per host",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "(sum(mongodb_sys_mounts_mnt_mongodb_capacity{onyxdb_cluster=~\"$cluster\", instance!=\"$hidden_host\"}) by (pod)) - (sum(mongodb_sys_mounts_mnt_mongodb_available{onyxdb_cluster=~\"$cluster\", instance!=\"$hidden_host\"}) by (pod))",
       "legendFormat": "{{database}}"
      }
     ]
    },
    {
     "title": "Disk space usage per host",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "((sum(mongodb_sys_mounts_mnt_mongodb_capacity{onyxdb_cluster=~\"$cluster\", instance!=\"$hidden_host\"}) by (pod)) - (sum(mongodb_sys_mounts_mnt_mongodb_available{onyxdb_cluster=~\"$cluster\", instance!=\"$hidden_host\"}) by (pod))) / (sum(mongodb_sys_mounts_mnt_mongodb_capacity{onyxdb_cluster=~\"$cluster\", instance!=\"$hidden_host\"}) by (pod)) * 100",
       "legendFormat": "{{database}}"
      }
     ]
    },
    {
     "title": "Disk writes + reads per host",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 101 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "rate(\n    sum(mongodb_sys_disks_nvme0n1_writes{mongodb_cluster_name=~\"$cluster\", instance!=\"$hidden_host\"}) by (instance) +\n    sum(mongodb_sys_disks_nvme0n1_reads{mongodb_cluster_name=~\"$cluster\", instance!=\"$hidden_host\"}) by (instance) \n)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Disk writes per host",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 101 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "rate(sum(mongodb_sys_disks_nvme0n1_writes{onyxdb_cluster=~\"$cluster\", instance!=\"$hidden_host\"}) by (pod))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Disk reads per host",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 101 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "rate(\n    sum(mongodb_sys_disks_nvme0n1_reads{onyxdb_cluster=~\"$cluster\", instance!=\"$hidden_host\"}) by (pod)\n)",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "WiredTriger Metrics for $cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 }
  },
  {
   "title": "WiredTiger checkpoint time on primary",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(mongodb_ss_wt_txn_transaction_checkpoint_most_recent_time_msecs{onyxdb_cluster=~\"$cluster\", rs_state=\"1\", instance!=\"$hidden_host\"})",
     "legendFormat": "mongodb_ss_wt_txn_transaction_checkpoint_most_recent_time_msecs"
    },
    {
     "expr": "sum(mongodb_ss_wt_txn_transaction_checkpoint_max_time_msecs{mongodb_cluster_name=~\"$cluster\", rs_state=\"1\", instance!=\"$hidden_host\"})",
     "legendFormat": "mongodb_ss_wt_txn_transaction_checkpoint_max_time_msecs"
    },
    {
     "expr": "sum(mongodb_ss_wt_txn_transaction_checkpoint_min_time_msecs{mongodb_cluster_name=~\"$cluster\", rs_state=\"1\", instance!=\"$hidden_host\"}) by (job)",
     "legendFormat": "mongodb_ss_wt_txn_transaction_checkpoint_min_time_msecs"
    }
   ]
  },
  {
   "title": "WiredTiger cache state on primary",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "sum(mongodb_ss_wt_cache_tracked_dirty_bytes_in_the_cache{onyxdb_cluster=~\"$cluster\", rs_state=\"1\", instance!=\"$hidden_host\"})",
     "legendFormat": "mongodb_ss_wt_cache_tracked_dirty_bytes_in_the_cache"
    },
    {
     "expr": "sum(mongodb_ss_wt_cache_maximum_bytes_configured{mongodb_cluster_name=~\"$cluster\", rs_state=\"1\", instance!=\"$hidden_host\"})",
     "legendFormat": "mongodb_ss_wt_cache_maximum_bytes_configured"
    },
    {
     "expr": "sum(mongodb_ss_wt_cache_bytes_currently_in_the_cache{mongodb_cluster_name=~\"$cluster\", rs_state=\"1\", instance!=\"$hidden_host\"})",
     "legendFormat": "mongodb_ss_wt_txn_transaction_checkpoint_min_time_msecs"
    }
   ]
  },
  {
   "title": "WiredTiger transactions state on primary",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(sum(mongodb_ss_wt_txn_transaction_begins{onyxdb_cluster=~\"$cluster\", rs_state=\"1\", instance!=\"$hidden_host\"}))",
     "legendFormat": "mongodb_ss_wt_txn_transaction_begins"
    },
    {
     "expr": "rate(sum(mongodb_ss_wt_txn_transactions_committed{mongodb_cluster_name=~\"$cluster\", rs_state=\"1\", instance!=\"$hidden_host\"}))",
     "legendFormat": "mongodb_ss_wt_txn_transactions_committed"
    },
    {
     "expr": "rate(sum(mongodb_ss_wt_txn_transactions_rolled_back{mongodb_cluster_name=~\"$cluster\", rs_state=\"1\", instance!=\"$hidden_host\"}))",
     "legendFormat": "mongodb_ss_wt_txn_transactions_rolled_back"
    }
   ]
  },
  {
   "title": "WiredTiger transactions state on primary",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(mongodb_ss_wt_concurrentTransactions_out{onyxdb_cluster=~\"$cluster\", instance!=\"$hidden_host\"}) by (txn_rw)",
     "legendFormat": "mongodb_ss_wt_concurrentTransactions_out.{{txn_rw}}"
    },
    {
     "expr": "sum(mongodb_ss_wt_concurrentTransactions_totalTickets{mongodb_cluster_name=~\"$cluster\", instance!=\"$hidden_host\"}) by (txn_rw)",
     "legendFormat": "mongodb_ss_wt_concurrentTransactions_totalTickets.{{txn_rw}}"
    }
   ]
  },
  {
   "title": "WiredTiger cache pages evicted on primary",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(sum(mongodb_ss_wt_cache_modified_pages_evicted{onyxdb_cluster=~\"$cluster\", instance!=\"$hidden_host\"}))",
     "legendFormat": "mongodb_ss_wt_cache_modified_pages_evicted"
    },
    {
     "expr": "rate(sum(mongodb_ss_wt_cache_unmodified_pages_evicted{mongodb_cluster_name=~\"$cluster\", instance!=\"$hidden_host\"}))",
     "legendFormat": "mongodb_ss_wt_cache_unmodified_pages_evicted"
    }
   ]
  }
 ]
}