apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  labels:
    app: grafana
data:
  grafana.ini: |
    [security]
    allow_embedding = true
    [cors]
    allow_origin = "*"
    allow_methods = "GET,POST,OPTIONS"
    allow_headers = "accept,authorization,content-type,origin"
