name: "Build Docker image"

on:
  workflow_call:
    secrets:
      DOCKER_LOGIN:
        required: true
      DOCKER_PASSWORD:
        required: true
  workflow_dispatch:

env:
  MASTER_BRANCH: master
  BRANCH_NAME: ${{github.head_ref || github.ref_name}}
  DOCKER_REPOSITORY: foxleren/onyxdb

jobs:
  build-push-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{env.BRANCH_NAME}}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_LOGIN}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: corretto

      - uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Build Docker image
        run: docker build -t ${{env.DOCKER_REPOSITORY}} -f ./docker/onyxdb.dockerfile .

      - name: Tag Docker image
        run: |
          docker tag ${{env.DOCKER_REPOSITORY}} ${{env.DOCKER_REPOSITORY}}:${{env.BRANCH_NAME}}-${GITHUB_SHA::7}

      - name: Push Docker image
        run: |
          docker push ${{env.DOCKER_REPOSITORY}}:${{env.BRANCH_NAME}}-${GITHUB_SHA::7}
