name: 'Run checks'

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  full-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: corretto

      - uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        run: ./gradlew clean onyxdbGenerateAllCodegen build
