name: 'heavy-check'

on:
  schedule:
    # Github-actions don't support custom timezone for cron expression,so it is UTC timezone.
    - cron: '0 18 * * *'
  workflow_dispatch:

jobs:
  build-with-codegen:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: corretto

      - uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        run: ./gradlew clean onyxdbGenerateAllCodegen build
