name: 'Generate all codegen and build monorepo'

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build-with-codegen:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: corretto

      - uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        run: ./gradlew clean onyxdbGenerateAllCodegen build
